### ISSUE TITLE
Improve CompositeAction.ActionItem

### ISSUE THREAD

**Issue by NaikSoftware** [drstranges/ActionHandler#2]
Great project!
Please add support for TitleProvider in CompositeAction.ActionItem and support for set String as title (at now supports only string-res int)
Thanks.

**Comment by drstranges** [comment]
Added in release [0.1.17](https://github.com/drstranges/ActionHandler/releases/tag/v0.1.17)

**Comment by NaikSoftware** [comment]
Thanks for great job bro
